# -*- coding: utf-8 -*-
"""ExpenseTracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1od1kprcVbFqgW6XjG--1tFqAt0L3994I
"""

!pip install pandas matplotlib

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

# Initialize an empty DataFrame to store expenses
expenses_df = pd.DataFrame(columns=['Date', 'Category', 'Description', 'Amount'])

# Function to add an expense
def add_expense(date, category, description, amount):
    global expenses_df
    new_expense = pd.DataFrame([[date, category, description, amount]], columns=['Date', 'Category', 'Description', 'Amount'])
    expenses_df = pd.concat([expenses_df, new_expense], ignore_index=True)
    print("Expense added successfully.")

# Function to view all expenses
def view_expenses():
    if expenses_df.empty:
        print("No expenses to display.")
    else:
        display(expenses_df)

# Function to generate a summary of expenses
def expense_summary():
    if expenses_df.empty:
        print("No expenses to summarize.")
    else:
        summary = expenses_df.groupby('Category').agg({'Amount': 'sum'}).reset_index()
        display(summary)

        # Plotting the summary
        plt.figure(figsize=(10, 5))
        plt.bar(summary['Category'], summary['Amount'])
        plt.xlabel('Category')
        plt.ylabel('Amount')
        plt.title('Expense Summary by Category')
        plt.show()

def main():
    while True:
        print("\nExpense Tracker Menu")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Expense Summary")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            date = input("Enter date (YYYY-MM-DD): ")
            category = input("Enter category: ")
            description = input("Enter description: ")
            amount = float(input("Enter amount: "))
            add_expense(date, category, description, amount)
        elif choice == '2':
            view_expenses()
        elif choice == '3':
            expense_summary()
        elif choice == '4':
            print("Exiting Expense Tracker.")
            break
        else:
            print("Invalid choice. Please try again.")

# Run the main function to start the expense tracker
main()

